image:
  repository: ozhank/python-helloworld
  tag: 3.2.3
replicaCount: 2
hpa:
  enabled: true
canary:
  enabled: true
ingress:
  enabled: true
  path: /
  hosts:
  - python-helloworld-prod.t2.zebrastack.com
  tls:
  - hosts:
    - python-helloworld-prod.t2.zebrastack.com
    secretName: ingress-cert-t2

